### ISSUE TITLE
Confusing double negative in the Lyon ammendment

### ISSUE THREAD

**Issue by djzort** [Perl-Toolchain-Gang/toolchain-site#13]
This phrase features a double negative which makes it confusing. Just like an "unless ! $foo" statement.

> No new release distribution in the Perl toolchain will specify a minimum perl prerequisite version (whether configure, build, runtime, or test) that has not been available for at least ten years.

Rather than a no-not statement, it would be more easily understood as a statement of what will happen rather than what no-not will happen.

Its probably too l late, but a better statement would be something like

> New releases of the Perl toolchain shall specify a minimum perl prerequisite version (whether configure, build, runtime, or test) that was released at least ten years prior.

**Comment by Leont** [comment]
> Its probably too l late, but a better statement would be something like

I don't think it's too late for textual improvement, and you're not the first one whom I've seen made a comment about that line.

**Comment by kenahoo** [comment]
Yes - though I would keep "available for at least ten years", not change it to "released at least ten years prior", because I don't know whether the latter means "now - year of release >= 10" or "year of release >= now-10", which are opposites.

**Comment by djzort** [comment]
It would be worth clarifying the what "available" has been agreed to mean, since it is not being used as a synonym for the release date of the tar ball

**Comment by mohawk2** [comment]
@djzort I would encourage you to keep banging at this until you're happy it's clear to you and the wider world. A word here or there now might save a significant amount of agony not very far down the line!

**Comment by djzort** [comment]
Right now it's not clear what the intent of the amendment is, which is unfortunate. Hopefully someone who was there and who was involved in the decision can help describe the intent of the decision.

**Comment by Leont** [comment]
How about: 

> No new release distribution in the Perl toolchain will specify a minimum perl prerequisite version (whether configure, build, runtime, or test) that has been available for less than ten years.

**Comment by rjbs** [comment]
I used Leon's text.  Shall we close this?
